# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import sms_collector_pb2 as sms__collector__pb2


class SmsCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CollectStatus = channel.unary_unary(
        '/sms_collector.SmsCollector/CollectStatus',
        request_serializer=sms__collector__pb2.StatusRequest.SerializeToString,
        response_deserializer=sms__collector__pb2.Response.FromString,
        )
    self.CollectVariable = channel.unary_unary(
        '/sms_collector.SmsCollector/CollectVariable',
        request_serializer=sms__collector__pb2.VariableRequest.SerializeToString,
        response_deserializer=sms__collector__pb2.Response.FromString,
        )


class SmsCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CollectStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectVariable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SmsCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CollectStatus': grpc.unary_unary_rpc_method_handler(
          servicer.CollectStatus,
          request_deserializer=sms__collector__pb2.StatusRequest.FromString,
          response_serializer=sms__collector__pb2.Response.SerializeToString,
      ),
      'CollectVariable': grpc.unary_unary_rpc_method_handler(
          servicer.CollectVariable,
          request_deserializer=sms__collector__pb2.VariableRequest.FromString,
          response_serializer=sms__collector__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sms_collector.SmsCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
